return { -- Highlight, edit, and navigate code
  'nvim-treesitter/nvim-treesitter',
  branch = 'main',
  lazy = false,
  build = ':TSUpdate',
  config = function()
    require('nvim-treesitter').install {
      'go',
      'gotmpl',
      'gomod',
      'gosum',
      'gowork',
      'bash',
      'c',
      'cpp',
      'html',
      'javascript',
      'jsdoc',
      'json',
      'kdl',
      'lua',
      'luadoc',
      'luap',
      'markdown',
      'markdown_inline',
      'nix',
      'proto',
      'python',
      'regex',
      'rust',
      'sql',
      'terraform',
      'hcl',
      'toml',
      'tsx',
      'typescript',
      'vim',
      'vimdoc',
      'yaml',
    }
  end,
}
