return { -- Highlight, edit, and navigate code
  'nvim-treesitter/nvim-treesitter',
  branch = 'main',
  lazy = false,
  build = ':TSUpdate',
  -- main = 'nvim-treesitter.configs',
  ---@type TSConfig
  ---@diagnostic disable-next-line: missing-fields
  opts = {
    -- Autoinstall languages that are not installed
    auto_install = true,
    highlight = { enable = true },
    indent = { enable = true },
    fold = { enable = true },
    ensure_installed = {
      'go',
      'gotmpl',
      'gomod',
      'gosum',
      'gowork',
      'bash',
      'c',
      'cpp',
      'html',
      'javascript',
      'jsdoc',
      'json',
      'jsonc',
      'kdl',
      'lua',
      'luadoc',
      'luap',
      'markdown',
      'markdown_inline',
      'nix',
      'proto',
      'python',
      'regex',
      'rust',
      'sql',
      'terraform',
      'hcl',
      'toml',
      'tsx',
      'typescript',
      'vim',
      'vimdoc',
      'yaml',
    },
  },
}
